import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Wrapper from '@/layouts/Wrapper';
import Head from 'next/head';
import { FirebaseAppProvider } from 'reactfire';
import { firebaseConfig } from '@/lib/firebase';

export default function App({
	Component,
	pageProps,
}: AppProps & { Component: { layout: boolean } }) {
	const layout = (Component.layout ??= true);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<FirebaseAppProvider firebaseConfig={firebaseConfig}>
				{layout ? (
					<Wrapper>
						<Component {...pageProps} />
					</Wrapper>
				) : (
					<Component {...pageProps} />
				)}
			</FirebaseAppProvider>
		</>
	);
}
